### ISSUE TITLE
TypeError from using RE1_firmware_updater.py

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_factory#26]
Running on my Python3/Ubuntu 20.04 laptop, with a stepper PCB acting as the lift, I get the following error. I used the same command earlier today to flash P1 firmware using the `--install_path` option on the board with no problems.

```bash
binitshah@binitshah:~$ RE1_firmware_updater.py --lift --install
Collecting information...
.....

Traceback (most recent call last):
  File "/home/binitshah/.local/bin/RE1_firmware_updater.py", line 112, in <module>
    if not u.startup():
  File "/home/binitshah/.local/lib/python3.8/site-packages/stretch_factory/firmware_updater.py", line 332, in startup
    if self.__check_arduino_cli_install():
  File "/home/binitshah/.local/lib/python3.8/site-packages/stretch_factory/firmware_updater.py", line 358, in __check_arduino_cli_install
    version=res[res.find('Version:')+9:res.find(' Commit')]
TypeError: argument should be integer or bytes-like object, not 'str'
```

Getting similar error when using the `--install_branch` and `--install_path` options too.

**Comment by aedsinger** [comment]
Resolved in v0.1.9
